# repchain配置文件，可将文件复制到yml中，springboot需要自己封装bean，若感觉此部分内容较多也可以持久化到数据库中
repchain:
  # repchain 地址
  host: 192.168.2.76:8081
  # 接口协同信息此处为list可以配置多个
  interCo:
    # 用户标识
    - creditCode: 951002007l78123233
      # 证书名称
      certName: super_admin
      # 证书
      cert: -----BEGIN CERTIFICATE-----
        MIIBYzCCAQigAwIBAgIEXe8B6zAKBggqhkjOPQQDAjA5MREwDwYDVQQKDAhyZXBj
        aGFpbjEOMAwGA1UECwwFaXNjYXMxFDASBgNVBAMMC3N1cGVyX2FkbWluMB4XDTE5
        MTIxMDAyMjQ0M1oXDTIwMTIwOTAyMjQ0M1owOTERMA8GA1UECgwIcmVwY2hhaW4x
        DjAMBgNVBAsMBWlzY2FzMRQwEgYDVQQDDAtzdXBlcl9hZG1pbjBZMBMGByqGSM49
        AgEGCCqGSM49AwEHA0IABK9m+cb8jaYQ+ts/hK4INuQbOwAwoIhVa3uaRxsOsgoR
        +QaPuwcZAIbGWSa9bn8oGjSBDQutmE5XONbdiDwPRtwwCgYIKoZIzj0EAwIDSQAw
        RgIhAKZto+39OFced9YDaXYkOLrLcKD+8RbF57vzHpJrnFd1AiEAhNEK8MOsAlhM
        eRZmlXsq4KsvQFs+Wav9N9qJ+GGRpCs=
        -----END CERTIFICATE-----
      # 加密私钥
      privateKey: -----BEGIN ENCRYPTED PRIVATE KEY-----
        MIHUMD8GCSqGSIb3DQEFDTAyMBoGCSqGSIb3DQEFDDANBAg1+P5snkrhWgIBZDAU
        BggqhkiG9w0DBwQIenlxow1YzdIEgZB8q8RyYheLMgYbsNO12ZStj8NZfNd+2GC4
        XU8C2inwh1qpEfjaFQqhvr9nY2BvlE5WPO33yYAVv7PUVGyGZterykrI6c2XUfPN
        W45jFOzme6y8lhbVpefg0GU7mU/AITL5gOV7iJcQG0iyvplHP4TEjVFj3zM+ow4b
        cBuNWzA6z01Mq4DJCwJwPNxi9H2yc0U=
        -----END ENCRYPTED PRIVATE KEY-----
      # 私钥设置的密码
      password: 123456
      # 内容hash算法
      algo_hash: SHA256withECDSA
      # 内容签名算法
      algo_sign: SHA256withECDSA
      # 签名证书对应的请求方id和服务方id可在dashboard查看
      services:
        # 调用方id
        - e_from: 15cc9e361632986505972
          # 调用方host，服务方可以不写此处地址及端口号，若为异步调用，调用方会将数据写入header中
          from_host: localhost
          # 调用方端口
          from_port: 8889
          # 服务提供方id
          e_to: 1098aa9d1632986347443
          # 服务方地址
          to_host: localhost
          # 服务方端口
          to_port: 8888
          # 服务方证书
          from_cert: -----BEGIN CERTIFICATE-----
            MIIBYzCCAQigAwIBAgIEXe8B6zAKBggqhkjOPQQDAjA5MREwDwYDVQQKDAhyZXBj
            aGFpbjEOMAwGA1UECwwFaXNjYXMxFDASBgNVBAMMC3N1cGVyX2FkbWluMB4XDTE5
            MTIxMDAyMjQ0M1oXDTIwMTIwOTAyMjQ0M1owOTERMA8GA1UECgwIcmVwY2hhaW4x
            DjAMBgNVBAsMBWlzY2FzMRQwEgYDVQQDDAtzdXBlcl9hZG1pbjBZMBMGByqGSM49
            AgEGCCqGSM49AwEHA0IABK9m+cb8jaYQ+ts/hK4INuQbOwAwoIhVa3uaRxsOsgoR
            +QaPuwcZAIbGWSa9bn8oGjSBDQutmE5XONbdiDwPRtwwCgYIKoZIzj0EAwIDSQAw
            RgIhAKZto+39OFced9YDaXYkOLrLcKD+8RbF57vzHpJrnFd1AiEAhNEK8MOsAlhM
            eRZmlXsq4KsvQFs+Wav9N9qJ+GGRpCs=
            -----END CERTIFICATE-----
          # 调用方证书
          to_cert: -----BEGIN CERTIFICATE-----
            MIIBYzCCAQigAwIBAgIEXe8B6zAKBggqhkjOPQQDAjA5MREwDwYDVQQKDAhyZXBj
            aGFpbjEOMAwGA1UECwwFaXNjYXMxFDASBgNVBAMMC3N1cGVyX2FkbWluMB4XDTE5
            MTIxMDAyMjQ0M1oXDTIwMTIwOTAyMjQ0M1owOTERMA8GA1UECgwIcmVwY2hhaW4x
            DjAMBgNVBAsMBWlzY2FzMRQwEgYDVQQDDAtzdXBlcl9hZG1pbjBZMBMGByqGSM49
            AgEGCCqGSM49AwEHA0IABK9m+cb8jaYQ+ts/hK4INuQbOwAwoIhVa3uaRxsOsgoR
            +QaPuwcZAIbGWSa9bn8oGjSBDQutmE5XONbdiDwPRtwwCgYIKoZIzj0EAwIDSQAw
            RgIhAKZto+39OFced9YDaXYkOLrLcKD+8RbF57vzHpJrnFd1AiEAhNEK8MOsAlhM
            eRZmlXsq4KsvQFs+Wav9N9qJ+GGRpCs=
            -----END CERTIFICATE-----

