# repchain配置文件
repchain:
  # repchain 地址
  host: 192.168.2.76:8081
  # 同步区块高度
  height: 0
  # 用户唯一标识
  creditCode: CGZL7XOwwa
  # 证书名称
  certName: test
  # 证书
  cert: -----BEGIN CERTIFICATE-----
    MIIBIDCBx6ADAgECAgQDNHtwMAoGCCqGSM49BAMCMA8xDTALBgNVBAMMBFRFU1Qw
    IhgPMjAyMTEwMjYwMTE0MDVaGA85OTk5MTIzMTIzNTk1OVowDzENMAsGA1UEAwwE
    VEVTVDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABO3voNU9OV4EoDyBHQcD+az/
    E5TB1i5fRf+tTaNgjCWr6jErt/Ce21b18uwTuZXx38nvA5l26S1MEpCAuuJSFymj
    DTALMAkGA1UdIwQCMAAwCgYIKoZIzj0EAwIDSAAwRQIhANjTlEKVu0O5lgEloHrh
    ZLcNMHH9S2sVzasTK5OJuXwGAiBGi2GL4W4XlWzjl94swApuv2bb7rbo2huBIzhc
    zZXMcw==
    -----END CERTIFICATE-----
  # 加密私钥
  privateKey: -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIHUMD8GCSqGSIb3DQEFDTAyMBoGCSqGSIb3DQEFDDANBAi0q5jmLN61vAIBZDAU
    BggqhkiG9w0DBwQITUCFquFjnwEEgZAbZouweJPtR6zRaDhULbyzF3uaOnMErtx3
    kIguDP/qeb3wVoTW8kFuOw1jdrY5WyHGCngfpM5br6AUaEqIlBnA7rS3KZfhsxxq
    yLQcaySsfUowUE61oStDJtDgHMJE0dbxuYXjnzSQrnp9AnnX65uwUeDE6c+i7DnW
    pWoroVTXK/dQb4vWNmxmacQ6G8jmW0s=
    -----END ENCRYPTED PRIVATE KEY-----
  # 私钥设置的密码
  password: 123456
  # 签名证书对应的请求方id和服务方id可在dashboard查看
  services:
    # 用户自定义id，不能重复，必填
    - serviceId: 1
      # 提供方证书
      e_from: bb743c821635920387678
      # 服务方证书
      from_cert: -----BEGIN CERTIFICATE-----
        MIIBIDCBx6ADAgECAgQDNHtwMAoGCCqGSM49BAMCMA8xDTALBgNVBAMMBFRFU1Qw
        IhgPMjAyMTEwMjYwMTE0MDVaGA85OTk5MTIzMTIzNTk1OVowDzENMAsGA1UEAwwE
        VEVTVDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABO3voNU9OV4EoDyBHQcD+az/
        E5TB1i5fRf+tTaNgjCWr6jErt/Ce21b18uwTuZXx38nvA5l26S1MEpCAuuJSFymj
        DTALMAkGA1UdIwQCMAAwCgYIKoZIzj0EAwIDSAAwRQIhANjTlEKVu0O5lgEloHrh
        ZLcNMHH9S2sVzasTK5OJuXwGAiBGi2GL4W4XlWzjl94swApuv2bb7rbo2huBIzhc
        zZXMcw==
        -----END CERTIFICATE-----
      # 服务提供方id
      e_to: 7b5c66df1635920342945
      # 调用方证书
      to_cert: -----BEGIN CERTIFICATE-----
        MIIBIDCBx6ADAgECAgQDNHtwMAoGCCqGSM49BAMCMA8xDTALBgNVBAMMBFRFU1Qw
        IhgPMjAyMTEwMjYwMTE0MDVaGA85OTk5MTIzMTIzNTk1OVowDzENMAsGA1UEAwwE
        VEVTVDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABO3voNU9OV4EoDyBHQcD+az/
        E5TB1i5fRf+tTaNgjCWr6jErt/Ce21b18uwTuZXx38nvA5l26S1MEpCAuuJSFymj
        DTALMAkGA1UdIwQCMAAwCgYIKoZIzj0EAwIDSAAwRQIhANjTlEKVu0O5lgEloHrh
        ZLcNMHH9S2sVzasTK5OJuXwGAiBGi2GL4W4XlWzjl94swApuv2bb7rbo2huBIzhc
        zZXMcw==
        -----END CERTIFICATE-----
## 中间件配置
middleware:
  # 文件配置
  file:
    # 文件持久化配置
    temp: /file/tmp
    # 文件备份地址配置
    backupPath: /data/backup
  # 日志配置
#  log:
    # 日志保存路径
#    path: /data/logs
  # 持久化
  persistence:
    # 接收的请求数据是否持久化，此处会持久化所配置的数据库
    receiveSave: false
  # 用来访问服务方提供的接口的客户端
  recClient:
    host: 127.0.0.1
    port: 80
    # http
    protocol: http
    # 超时时间
    timeout: 5000
  # 用来让调用方访问的服务器
  recServer:
    # 端口
    port: 8888
    # 初始线程池大小
    corePoolSize: 50
    # 最大线程池大小
    maxPoolSize: 200
    # 队列，用于存在未执行的线程
    workQueue: 100
  # 中间件之间通信的客户端
  comClient:
    timeout: 5000
    maxTotal: 8
    minIdle: 1
    maxIdle: 8
    maxWaitMillis: -1
    lifo: true
    minEvictableIdleTimeMillis: 1800000
    blockWhenExhausted: true
  # 中间件之间通信的服务器
  comServer:
    # 端口
    port: 8080
    # 初始线程池大小
    corePoolSize: 50
    # 最大线程池大小
    maxPoolSize: 200
    # 队列，有用存储未执行的线程
    workQueue: 100
# 数据源配置，用于数据持久化，当前版本只支持sqlite
datasource:
#  url: jdbc:sqlite:data/repchain_mid.db
#  pass: root
#  user: root
#  driver: org.sqlite.JDBC
  url: jdbc:mysql://192.168.2.76:3306/repchain_mid?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  pass: root
  user: root
  driver: com.mysql.jdbc.Driver
  ## 可选配置
  # 是否在日志中显示执行的SQL
  showSql: true
  # 是否格式化显示的SQL
  formatSql: true
  # 是否显示SQL参数
  showParams: true
  # 打印SQL的日志等级，默认debug，可以是info、warn、error
  sqlLevel: debug
