# repchain配置文件
repchain:
  # 组网Id
  chainNetworkId: identity-net
  # repchain 地址
  host: 192.168.1.167:9081
  # 同步区块高度
  height: 0
  # 出块时间 (分钟）
  blockTime: 5
  # 用户唯一标识
  creditCode: identity-net:ZR8WDi2DJ9
  # 证书名称
  certName: diaoyong
  # 证书
  cert: -----BEGIN CERTIFICATE-----
    MIIBSTCB8aADAgECAgQHtnBwMAoGCCqGSM49BAMCMBMxETAPBgNVBAMMCERJQU9Z
    T05HMCIYDzIwMjIwNjE1MDUzNTU2WhgPOTk5OTEyMzEyMzU5NTlaMBMxETAPBgNV
    BAMMCERJQU9ZT05HMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEj8WFs3RmepyF
    mXMUZS1QLfTL8EUnB2SV5VGo2qlfqxY2F1LzHwLSPXJpviN8Mpl7mlzW6VzSiQH+
    HO7xubhb5KMvMC0wKwYDVR0jBCQwIoAg+/o+yzVvnIp6qH4JMJRQQHYvHX3u26d4
    lnQVWXkdH3EwCgYIKoZIzj0EAwIDRwAwRAIgDslUkkhKNh3RCrhSXbWbHlkVg7SH
    /yuZYyu0523OoEICIA5HyA8Z6gXd4JsGdJsmwT3+fLGqnG5lM/gv7Djg7fin
    -----END CERTIFICATE-----
  # 加密私钥
  privateKey: -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIHUMD8GCSqGSIb3DQEFDTAyMBoGCSqGSIb3DQEFDDANBAg2Xue/BAHwRgIBZDAU
    BggqhkiG9w0DBwQI7QhxvgSKm9sEgZBvKQF5qRDXVHSxvhxwPbSr6X66xSKNmB04
    idei9BrczwSbHWUqj6Pr139B+pw2SoqtZf0v/3OUbYWv5sOrtWJk32zVTL2zGlhn
    y5Ig1s6++HKdkXYSRH5+At4kuYVAQfcyLk8xlm1yK+HmFVOkXjz3Ta9zqaeeu9BW
    310n5pULGujrNXiVc3sJH45coJ7/Q5k=
    -----END ENCRYPTED PRIVATE KEY-----
  # 私钥设置的密码
  password: 123456
  # 签名证书对应的请求方id和服务方id可在dashboard查看
  services:
    # 用户自定义id，不能重复，必填
    - serviceId: 1
      # 调用方ID
      e_from: fbb561061655349904075
      # 调用方证书
      from_cert: -----BEGIN CERTIFICATE-----
        MIIBSTCB8aADAgECAgQHtnBwMAoGCCqGSM49BAMCMBMxETAPBgNVBAMMCERJQU9Z
        T05HMCIYDzIwMjIwNjE1MDUzNTU2WhgPOTk5OTEyMzEyMzU5NTlaMBMxETAPBgNV
        BAMMCERJQU9ZT05HMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEj8WFs3RmepyF
        mXMUZS1QLfTL8EUnB2SV5VGo2qlfqxY2F1LzHwLSPXJpviN8Mpl7mlzW6VzSiQH+
        HO7xubhb5KMvMC0wKwYDVR0jBCQwIoAg+/o+yzVvnIp6qH4JMJRQQHYvHX3u26d4
        lnQVWXkdH3EwCgYIKoZIzj0EAwIDRwAwRAIgDslUkkhKNh3RCrhSXbWbHlkVg7SH
        /yuZYyu0523OoEICIA5HyA8Z6gXd4JsGdJsmwT3+fLGqnG5lM/gv7Djg7fin
        -----END CERTIFICATE-----
      # 服务提供方id
      e_to: 5d4439241655349362917
      # 提供方证书
      to_cert: -----BEGIN CERTIFICATE-----
        MIIBHjCBxaADAgECAgQimh/AMAoGCCqGSM49BAMCMA4xDDAKBgNVBAMMA2xoYzAi
        GA8yMDIxMTEyMzAzMTIwNVoYDzk5OTkxMjMxMjM1OTU5WjAOMQwwCgYDVQQDDANs
        aGMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQuOTBhmuWl5cTI+w2apLboHEgJ
        fiKYtoe7KTltmvMgKtDhvcG4v0TEZlnEfMidFsR985dZczVmPnoSw3jOSzFeow0w
        CzAJBgNVHSMEAjAAMAoGCCqGSM49BAMCA0gAMEUCICcx+P4IoHwfYEmqU6eU7D7W
        7N5p83onIbkJt9+9+WhdAiEA4EoS3QoLIjLe+SkR3ixVsNg4faefkvZ4cQwwGCoH
        DSw=
        -----END CERTIFICATE-----
## 中间件配置
middleware:
    # 文件配置
  file:
    # 文件缓冲大小，如果文件传输速度较慢，可以增大此参数，此参数推荐1024的倍数
    bufferSize: 8192
  #    # 文件持久化配置
  #    temp: /file/tmp
  #    # 文件备份地址配置
  #    backupPath: /data/backup
  # 日志配置
  #  log:
  # 日志保存路径
  #    path: /data/logs
  # 用来访问服务方提供的接口的客户端
  recClient:
    host: localhost
    port: 8888
    # http
    protocol: http
    # 超时时间
    timeout: 30000
  # 用来让调用方访问的服务器
  recServer:
    # 端口
    port: 8888
    # 初始线程池大小
    corePoolSize: 50
    # 最大线程池大小
    maxPoolSize: 200
    # 队列，用于存在未执行的线程
    workQueue: 100
  # 中间件之间通信的客户端
  comClient:
    # 超时时间（毫秒）
    timeout: 5000
    # 池中的最大连接数
    maxTotal: 8
    # 最少的空闲连接数
    minIdle: 1
    # 最多的空闲连接数
    maxIdle: 8
    # 当连接池资源耗尽时,调用者最大阻塞的时间,超时时抛出异常 单位:毫秒数
    maxWaitMillis: -1
    # 连接池存放池化对象方式,true放在空闲队列最前面,false放在空闲队列最后
    lifo: true
    # 连接空闲的最小时间,达到此值后空闲连接可能会被移除,默认即为30分钟
    minEvictableIdleTimeMillis: 1800000
    # 连接耗尽时是否阻塞,默认为true
    blockWhenExhausted: true
  # 中间件之间通信的服务器
  comServer:
    # 端口
    port: 9090
    # 初始线程池大小
    corePoolSize: 50
    # 最大线程池大小
    maxPoolSize: 200
    # 队列，有用存储未执行的线程
    workQueue: 100
# 数据源配置，用于数据持久化，当前版本支持sqlite，mysql
datasource:
  #  url: jdbc:sqlite:data/repchain_mid.db
  #  pass: root
  #  user: root
  #  driver: org.sqlite.JDBC
  url: jdbc:mysql://192.168.1.111:3306/repchain_mid?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  pass: root
  user: root
  driver: com.mysql.jdbc.Driver
  # 是否在日志中显示执行的SQL
  showSql: true
  # 是否格式化显示的SQL
  formatSql: true
  # 是否显示SQL参数
  showParams: true
  # 打印SQL的日志等级，默认debug，可以是info、warn、error
  sqlLevel: debug
